# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug4Ox4qIFDSo1koFA0XiNJE-ce12rECy

# Proyek Analisis Data: [Input Nama Dataset]
- **Nama:** [Input Nama]
- **Email:** [Input Email]
- **ID Dicoding:** [Input Username]

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1
- Pertanyaan 2

## Import Semua Packages/Library yang Digunakan
"""



"""## Data Wrangling

### Gathering Data
"""



"""**Insight:**
- xxx
- xxx

### Assessing Data
"""



"""**Insight:**
- xxx
- xxx

### Cleaning Data
"""



"""**Insight:**
- xxx
- xxx

## Exploratory Data Analysis (EDA)

### Explore ...
"""



"""**Insight:**
- xxx
- xxx

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""



"""### Pertanyaan 2:"""



"""**Insight:**
- xxx
- xxx

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Conclution pertanyaan 1
- Conclution pertanyaan 2
"""